			var overview = {
				"holz": "<img src='img/CHR/Holz.png' style='border: 1px solid black;width:25px;height: 25px'/>",
				"stein": "<img src='img/CHR/Stein.png' style='border: 1px solid black;width:25px;height: 25px'/>",
				"erz": "<img src='img/CHR/Erz.png' style='border: 1px solid black;width:25px;height: 25px'/>",
				"getreide": "<img src='img/CHR/Getreide.png' style='border: 1px solid black;width:25px;height: 25px'/>",
				"haus":"<img src='img/CHR/Gebäude.png' style='width:32px;height:32px;'/>",
				"krone":"<img src='img/CHR/Krone.png' style='width:32px;height:32px;'/>",
				"kreuz":"<img src='img/CHR/cross.png' style='width:32px;height:32px;'/>",
				"buch":"<img src='img/CHR/book.png' style='width:32px;height:32px;'/>",
				"kronewh":"<img src='img/CHR/Kronewhite.png' style='width:32px;height:32px;'/>",
				"kreuzwh":"<img src='img/CHR/crosswhite.png' style='width:32px;height:32px;'/>",
				"buchwh":"<img src='img/CHR/bookwhite.png' style='width:32px;height:32px;'/>",
			"cards": [
			{art : "H",Karte : "2", typ : "Holz" ,res1: "Holz"},
			{art : "S",Karte : "2", typ : "Stein" ,res1: "Stein"},
			{art : "E",Karte : "2", typ : "Erz" ,res1: "Erz"},
			{art : "G",Karte : "2", typ : "Getreide" ,res1: "Getreide"},
			{art : "H",Karte : "3", Punkt: "book", typ : "Holz" ,res1 : "Holz",res2: "Holz"},
			{art : "S",Karte : "3", Punkt: "cross", typ : "Stein", res1:"Stein" ,res2 : "Stein"},
			{art : "E",Karte : "3", Punkt: "Krone", typ : "Erz", res1: "Erz" ,res2 : "Erz"},
			{art : "G",Karte : "3", typ : "Getreide" , res1:"Getreide",res2 : "Getreide"},
			{art : "H",Karte : "4", Punkt: "book", typ : "Holz" ,res1 : "Holz",res2: "Holz"},
			{art : "S",Karte : "4", Punkt: "cross", typ : "Stein", res1: "Stein" ,res2 : "Stein"},
			{art : "E",Karte : "4", Punkt: "Krone", typ : "Erz",res1: "Erz", res2: "Erz"},
			{art : "G",Karte : "4", typ : "Getreide" ,res1: "Getreide",res2: "Getreide", pagebreak: true},

			{code: "H5", art : "H",Karte : "5", typ : "Gebäude", name : "Waldhütte", Kosten : "2 {{{holz}}}", Vorteil : "jede Runde: {{{holz}}}" ,res1 : "Holz"},
			{code: "H6", art : "H",Karte : "6", typ : "Gebäude", name : "Sägewerk", Kosten : "2 {{{erz}}}, 1 {{{stein}}}", Vorteil : "einmalig {{{holz}}} Max +2" ,res1 : "Holz"},
			{code: "S5", art : "S",Karte : "5", typ : "Gebäude", name : "Steinbruch", Kosten : "2 {{{stein}}}", Vorteil : "jede Runde: {{{stein}}}" ,res1 : "Stein"},
			{code: "S6", art : "S",Karte : "6", typ : "Gebäude", name : "Bergwerk", Kosten : "3 {{{stein}}}", Vorteil : "einmalig {{{stein}}} Max +2",res1 : "Stein"},
			{code: "E5", art : "E",Karte : "5", typ : "Gebäude", name : "Erzmine", Kosten : "1 {{{holz}}}, 1 {{{stein}}}", Vorteil : "jede Runde: {{{erz}}}" ,res1 : "1",res1 : "Erz"},
			{code: "E6", art : "E",Karte : "6", typ : "Gebäude", name : "Schürfmine", Kosten : "3 {{{holz}}}", Vorteil : "einmalig {{{erz}}} Max +2" ,res1 : "Erz"},
			{code: "G5", art : "G",Karte : "5", typ : "Gebäude", name : "Bauernhof", Kosten : "1 {{{holz}}}, 1 {{{getreide}}}", Vorteil : "jede Runde {{{getreide}}}+1" ,res1 : "Getreide"},
			{code: "G6", art : "G",Karte : "6", typ : "Gebäude", name : "Mühle", Kosten : "1 {{{stein}}}, 2 {{{holz}}}", Vorteil : "einmalig {{{getreide}}} max +2" ,res1 : "Getreide"},
			{code: "H7", art : "H",Karte : "7", Punkt: "book", typ : "Gebäude", name : "Heilhaus", Kosten : "3 {{{holz}}}, 2 {{{stein}}}", Vorteil : "Schutz vor Pest" ,res1 : "Holz"},
			{code: "H8", art : "H",Karte : "8", Punkt: "book", typ : "Gebäude", name : "Handelhaus", Kosten : "5 {{{holz}}}, 1 {{{stein}}}, 2 {{{erz}}}", Vorteil : "Bei jedem gewonnenen Stich 1 Karte von der Hand in die eigene Ablage" ,res1 : "Holz"},
			{code: "S7", art : "S",Karte : "7", Punkt: "cross",typ : "Gebäude", name : "Stadtmauer", Kosten : "4 {{{stein}}}", Vorteil : "Schutz vor Krieg",res1 : "Stein"},
			{code: "S8", art : "S",Karte : "8", Punkt: "cross", typ : "Gebäude", name : "Aquädukt", Kosten : "5 {{{stein}}}", Vorteil : "für 1 {{{holz}}} ein zusätzliche {{{buchwh}}}" ,res1 : "Stein", pagebreak: true},
			{code: "E7", art : "E",Karte : "7", Punkt: "Krone", typ : "Gebäude", name : "Miliz", Kosten : "2 {{{holz}}}, 2 {{{stein}}}", Vorteil : "Wird die eigene Warenkarte gestochen, darf man direkt 1 Karte vom Stapel auf die Hand ziehen." ,res1 : "Erz"},
			{code: "E8", art : "E",Karte : "8", typ : "Gebäude", name : "Schmelze", Kosten : "2 {{{holz}}}, 2 {{{stein}}}, 1 {{{erz}}}", Vorteil : "für 1 {{{erz}}} eine      zusätzliche {{{kronewh}}}" ,res1 : "Erz"},
			{code: "G7", art : "G",Karte : "7", typ : "Gebäude", name : "Marktplatz", Kosten : "3 {{{holz}}}, 1 {{{erz}}}", Vorteil : "Rundenbeginn: 1 Karte extra",res1 : "Getreide" },
			{code: "G8", art : "G",Karte : "8", typ : "Gebäude", name : "Trinkstuben", Kosten : "3 {{{holz}}}, 2 {{{stein}}}, 1 {{{erz}}}", Vorteil : "Rundenbeginn: 1 Karte extra" ,res1 : "Getreide" },
			{art : "H",Karte : "4", Punkt: "book", typ : "Apokalypse", name : "Feuersbrunst", Nachteil : "Nachteil: kein neues {{{holz}}}"},
			{art : "S",Karte : "4", Punkt: "cross", typ : "Apokalypse", name : "Pest", Nachteil : "Nachteil: kein neuer {{{stein}}}"},
			{art : "E",Karte : "4", Punkt: "Krone", typ : "Apokalypse", name : "Krieg", Nachteil : "Nachteil: kein neues {{{erz}}}" },
			{art : "G",Karte : "4", typ : "Apokalypse", name : "Sturm", Nachteil : "Nachteil: kein neues {{{getreide}}}."},

			{code: "H9", art : "H",Karte : "9", typ : "Gebäude", name : "Hafen", Kosten : "6 {{{holz}}}, 6 {{{stein}}}", Vorteil:"Deine Karten mit 2, 3 und 4 haben den Wert 5." ,res1 : "Holz"},
			{code: "S9", art : "S",Karte : "9", typ : "Gebäude", name : "Burg", Kosten : "8 {{{stein}}}, 2 {{{erz}}}", Vorteil : "kein Mitspieler kann Karten aus deiner Hand oder Ablage nehmen" ,res1 : "Stein"},
			{code: "E9", art : "E",Karte : "9", typ : "Gebäude", name : "Reiterhof", Kosten : "4 {{{holz}}}, 4 {{{stein}}}, 2 {{{erz}}}", Vorteil : "Rundenbeginn: 2 Karten zusätzlich ziehen und eine davon behalten." ,res1 : "Erz"},
			{code: "G9", art : "G",Karte : "9", Punkt: "book", typ : "Gebäude", name : "Rathaus", Kosten : "3 {{{erz}}}, 4 {{{holz}}}, 3 {{{stein}}}", Vorteil: "Die Punkte der neu gebauten Gebäude zählen doppelt.", res1 : "Getreide", pagebreak: true},

			{code: "H10", art : "H",Karte : "10", typ : "Gebäude", name : "Universität", Kosten : "8 {{{holz}}}, 5 {{{stein}}}, 7 {{{getreide}}}", Vorteil : "Siegpunkte am Ende der Partie verdoppeln." ,res1 : "Holz"},
			{code: "G10", art : "G",Karte : "10", Punkt: "Krone", typ : "Gebäude", name : "Schloss", Kosten : "7 {{{erz}}}, 7 {{{stein}}}, 1 {{{holz}}}", Vorteil : "1 Siegpunkt direkt", res1 : "Getreide"},
			{code: "E10", art : "E",Karte : "10", typ : "Gebäude", name : "Armee", Kosten : "5 {{{stein}}}, 5 {{{erz}}}, 5 {{{getreide}}}", Vorteil : "Vorteil: Zu Beginn der Runde je 1 Handkarte von den Spielern mit der grössten Bevölkerung ziehen." ,res1 : "Erz"},
			{code: "S10", art : "S",Karte : "10", typ : "Gebäude", name : "Festung", Kosten : "10 {{{stein}}}, 2 {{{erz}}}, 3 {{{holz}}}", Vorteil : "Ende der Runde: 1 Karte aus der Ablage für die nächste Runde behalten" ,res1 : "Stein"},
			
			{art : "H",Karte : "11", typ : "Person", name : "Krämer" ,res1 : "Holz", Stichbonus: "Stichbonus: 1 Karte aus der Ablage des Spielers mit der niedrigsten Karte."},
			{art : "G",Karte : "11", Punkt: "book", typ : "Person", name : "Händler", Vorteil : "Baubonus: alle {{{buchwh}}} zählen als zusätzliches {{{holz}}}." ,res1 : "Getreide"},
			{art : "S",Karte : "11", Punkt: "cross", typ : "Person", name : "Architekt", res1 : "Stein", Stichbonus: "Stichbonus: Im nächsten Stich erhöht deine Karte den Wert um 3"},
			{art : "E",Karte : "11", Punkt: "Krone", typ : "Person", name : "Baumeister", Vorteil: "Baubonus: alle {{{kronewh}}} zählen als zusätzliches {{{erz}}}"  ,res1 : "Erz"},

			{art : "S",Karte : "12", Punkt: "cross", typ : "Person", name : "Bischof", Vorteil: "Baubonus: alle {{{kreuzwh}}} zählen als zusätzliches {{{stein}}}" ,res1 : "Stein"},
			{art : "H",Karte : "12", Punkt: "book", typ : "Person", name : "Räuber", Stichbonus : "Stichbonus: 1 Karte von der Hand in die eigene Ablage." ,res1 : "Holz"},
			{art : "E",Karte : "12", Punkt: "Krone", typ : "Person", name : "Alchemist", Vorteil : "Baubonus: Schutz vor allen Apokalypsen." ,res1 : "Erz"},
			{art : "G",Karte : "12", typ : "Person", name : "Karawane", Vorteil : "Baubonus: nur ein {{{getreide}}} zur Ernährung der Bevölkerung nötig." ,res1 : "Getreide", pagebreak: true}
			

			]};
