			var overview = {
				"holz": "<img src='img/CHR/Holz.png' style='border: 1px solid black;width:25px;height: 25px'/>",
				"stein": "<img src='img/CHR/Stein.png' style='border: 1px solid black;width:25px;height: 25px'/>",
				"erz": "<img src='img/CHR/Erz.png' style='border: 1px solid black;width:25px;height: 25px'/>",
				"getreide": "<img src='img/CHR/Getreide.png' style='border: 1px solid black;width:25px;height: 25px'/>",
				"haus":"<img src='img/CHR/Gebäude.png' style='width:32px;height:32px;'/>",
				"krone":"<img src='img/CHR/Krone.png' style='width:32px;height:32px;'/>",
				"kreuz":"<img src='img/CHR/cross.png' style='width:32px;height:32px;'/>",
				"buch":"<img src='img/CHR/book.png' style='width:32px;height:32px;'/>",
				"kronewh":"<img src='img/CHR/Kronewhite.png' style='width:32px;height:32px;'/>",
				"kreuzwh":"<img src='img/CHR/crosswhite.png' style='width:32px;height:32px;'/>",
				"buchwh":"<img src='img/CHR/bookwhite.png' style='width:32px;height:32px;'/>",
			"cards": [
			{art : "H",Karte : "13", typ : "Person", name : "Papst", Stichbonus : "Stichbonus: sticht alle Karten mit {{{kreuzwh}}}.", res1 : "Holz"},
			{art : "S",Karte : "13", typ : "Person", name : "Baron", Stichbonus : "Stichbonus: sticht die beiden niedrgisten Karten." ,res1 : "Stein"},
			{art : "E",Karte : "13", Punkt: "book", typ : "Person", name : "Fürst", Stichbonus : "Stichbonus: sticht alle Karten mit {{{buchwh}}}." ,res1 : "Erz"},
			{art : "G",Karte : "13", Punkt: "Krone", typ : "Person", name : "König", "Stichbonus" : "Stichbonus: sticht alle Karten mit {{{kronewh}}}." ,res1 : "Getreide"},
			{art : "Df",Karte : "2", typ: "Dorf", name: "Siedler",Stichbonus: "{{{haus}}}{{{krone}}} +1 oder -1/+2 für ein {{{getreide}}}",res1: "Getreide",Punkt: "Krone"},
			{art : "Df",Karte : "3", typ: "Dorf", name: "Missernte", Nachteil : "{{{getreide}}} -1"},
			{art : "Df",Karte : "4", typ: "Dorf", name: "Bauernhof", Stichbonus: "{{{haus}}}{{{krone}}} +1 oder -1/+2 für ein {{{getreide}}}",res1: "Getreide"},

			{code: "Df5", art : "G",Karte : "5", typ: "Dorf", name: "Bauernhof", Kosten: "2 {{{holz}}}, 1 {{{stein}}}, 1 {{{erz}}}", Vorteil: "jede Runde: {{{getreide}}} +1" ,res1: "Holz",res2: "Getreide"},
			{code: "Df6", art : "G",Karte : "6", typ: "Dorf", name: "Bauernhof", Kosten: "2 {{{holz}}}, 1 {{{stein}}}, 1 {{{erz}}}", Vorteil: "jede Runde: {{{getreide}}} +1",res1: "Getreide",res2: "Holz"},
			{code: "Df7", art : "G",Karte : "7", typ: "Dorf", Punkt: "Krone", name: "grosser Hof", Kosten: "1 {{{erz}}}, 4 {{{holz}}}, 2 {{{stein}}}", Vorteil: "jede Runde: {{{getreide}}} +2" ,res1: "Getreide"},
			{code: "Df8", art : "G",Karte : "8", typ: "Dorf", Punkt: "Krone", name: "grosser Hof", Kosten: "1 {{{erz}}}, 4 {{{holz}}}, 2 {{{stein}}}", Vorteil: "jede Runde: {{{getreide}}} +2" ,res1: "Getreide"},
			{code: "Df9", art : "G",Karte : "9", typ: "Dorf", Punkt: "Krone", name: "Kloster", Vorteil: "Resourcenauswertung: Bev+1" , Kosten: "6 {{{stein}}}, 6 {{{holz}}}", res1: "Holz", pagebreak: true },
			{code: "Df10", art : "G",Karte : "10", typ: "Dorf", Punkt: "Krone" , name: "Fürstensitz", Kosten: "6 {{{stein}}}, 6 {{{holz}}}", Vorteil: "Handkarten ziehen: 2 Karten nachziehen und 2 ablegen."  ,res1: "Getreide",res2: "Erz"},

			{art : "H",Karte : "2", typ: "Markt", name: "Frondienst", Nachteil : "{{{holz}}} -1"},
			{art : "H",Karte : "3", typ: "Markt", name: "Siedler",Stichbonus: "{{{haus}}}{{{krone}}} +1 oder -1/+2 für ein {{{holz}}}",res1: "Getreide",Punkt: "cross"},
			{art : "H",Karte : "4", typ: "Markt", name: "Bauernhof", Stichbonus: "{{{haus}}}{{{krone}}} +1 oder -1/+2 für ein {{{holz}}}",res1: "Getreide"},
			{code: "Mk5", art : "H",Karte : "5", typ: "Markt", name: "Trockenleg.", Kosten: "4 {{{holz}}}, 1 {{{erz}}}", Vorteil: "Bauvorteil: jede Runde: {{{holz}}}+1, {{{stein}}}+1" ,res1: "holz",res2: "Stein"},
			{code: "Mk6", art : "H",Karte : "6", typ: "Markt", name: "Marktplatz", Kosten: "6 {{{holz}}}, 2 {{{erz}}}", Vorteil: "Bauvorteil: jede Runde: Resourcen können 1:1 gegen {{{getreide}}} getauscht werden",res1: "holz",res2: "Erz"},
			{code: "Mk7", art : "H",Karte : "7", typ: "Markt", name: "Flösserei", Kosten: "5 {{{holz}}}, 1 {{{stein}}}", Vorteil: "Bauvorteil: jede Runde: {{{holz}}} kann 1:1 gegen andere Resourcen geatuscht werden." ,res1: "holz"},
			{code: "Mk8", art : "H",Karte : "8", typ: "Markt", Punkt: "cross", name: "Mühle", Kosten: "4 {{{stein}}}, 4 {{{erz}}}", Vorteil: "Bauvorteil: jede Runde: {{{getreide}}} +3" ,res1: "holz",res2: "Stein"},
			{code: "Mk9", art : "H",Karte : "9", typ: "Markt", Punkt: "cross",name: "Klosterkirche", Kosten: " 8 {{{holz}}}, 6 {{{stein}}}", Vorteil: "Bauvorteil: Endauswertung: 2 Ruhmpunkte extra"  ,res1: "holz",res2: "Getreide"  },

			{art : "H",Karte : "2", typ: "Stadt", name: "Barbaren", Nachteil : "{{{stein}}} -1"},
			{art : "H",Karte : "3", typ: "Stadt", name: "Siedler",Stichbonus: "{{{haus}}}{{{krone}}} +1 oder -1/+2 für ein {{{stein}}}",res1: "Getreide",Punkt: "cross"},
			{art : "H",Karte : "4", typ: "Stadt", name: "Bauernhof", Stichbonus: "{{{haus}}}{{{krone}}} +1 oder -1/+2 für ein {{{stein}}}",res1: "Getreide", pagebreak: true},
			{code: "St5", art : "S",Karte : "5", typ: "Stadt", Punkt: "cross", name: "Kaserne", Kosten: "3 {{{erz}}}, 2 {{{stein}}}", Vorteil: "jede Runde: {{{erz}}}+1." ,res1: "Stein",res2: "Holz"},
			{code: "St6", art : "S",Karte : "6", typ: "Stadt", Punkt: "Krone", name: "Reiterhof", Kosten: "3 {{{erz}}}, 2 {{{stein}}}", Vorteil: "Bauvorteil: jede Runde: 1 Warenkarte von linken nachbarn nehmen.",res1: "Stein",res2: "Erz"},
			{code: "St7", art : "S",Karte : "7", typ: "Stadt", Punkt: "Krone", name: "Atilerie", Kosten: "5 {{{erz}}}, 1 {{{stein}}}", Vorteil: "Bauvorteil: jede Runde: 1 Warenkarte von rechtem Nachbarn nehmen." ,res1: "Stein"},
			{code: "St8", art : "S",Karte : "8", typ: "Stadt", name: "Generalsitz", Kosten: "4 {{{stein}}}, 4 {{{erz}}}", Vorteil: "Bauvorteil: Rundenauswertung: 2 Punkte extra" ,res1: "Stein",res2: "Erz"},
			{code: "St9", art : "S",Karte : "9", typ: "Stadt", name: "Residenz", Kosten: "6 {{{stein}}}, 6 {{{holz}}}", Vorteil: "Bauvorteil: Rundenauswertung: 3 Punkte extra"  ,res1: "Stein",res2: "Getreide"},

			{art : "E",Karte : "2", typ: "Großstadt", name: "Kriegsdienst", Nachteil : "{{{erz}}} -1"},
			{art : "E",Karte : "3", typ: "Großstadt", name: "Siedler",Stichbonus: "{{{haus}}}{{{krone}}} +1 oder -1/+2 für ein {{{erz}}}",res1: "Getreide",Punkt: "cross"},
			{art : "E",Karte : "4", typ: "Großstadt", name: "Bauernhof", Stichbonus: "{{{haus}}}{{{krone}}} +1 oder -1/+2 für ein {{{erz}}}",res1: "Getreide"},
			{code: "Gs5", art : "E",Karte : "5", typ: "Großstadt", Punkt: "book", name: "Trockenleg.",  Vorteil: "jede Runde: {{{holz}}}+1, Karte zu Gebäuden legen." ,res1: "Erz",res2: "Stein",art2: "S"},
			{code: "Gs6", art : "E",Karte : "6", typ: "Großstadt", name: "Sägewerk", Kosten: "3 {{{holz}}}, 1 {{{erz}}}", Vorteil: "Bauvorteil: jede Runde: {{{holz}}} +1",res1: "Erz",res2: "Stein",art2: "S"},
			{code: "Gs7", art : "E",Karte : "7", typ: "Großstadt", name: "Flösserei", Kosten: "5 {{{holz}}}, 1 {{{stein}}}", Vorteil: "Bauvorteil: jede Runde: {{{holz}}} +2" ,res1: "Erz"},
			{code: "Gs8", art : "E",Karte : "8", typ: "Großstadt", Punkt: "Krone", name: "Residenz", Kosten: "6 {{{stein}}}, 6 {{{holz}}}", Vorteil: "jede Runde: Alle Dorf und Marktspieler müssen dir eine Resource ihrer Wahl abgeben. ",res1: "Erz",res2: "Getreide"},
			{code: "Gs9", art : "E",Karte : "9", typ: "Großstadt", Punkt: "Krone", name: "Mühle", Kosten: "4 {{{stein}}}, 4 {{{erz}}}", Vorteil: "Bauvorteil: jede Runde: {{{getreide}}} +3" ,res1: "Erz",res2: "Stein"},
			{code: "Gs10", art : "E",Karte : "10", typ: "Großstadt", Punkt: "cross", name: "Kloster", Kosten: "6 {{{stein}}}, 6 {{{holz}}}", Vorteil: "Bauvorteil: Endauswertung: 2 Ruhmpunkte extra"  ,res1: "Erz",res2: "Getreide"}

			]};
